### ISSUE TITLE
ListView setOnItemClickListener not working

### ISSUE THREAD

**Issue by finicu212** [UPB-FILS-MDAD/questions#1]
I'm trying to open an activity that displays details about the selected movie when that movie's list item is clicked. However, even after adding an `OnItemClickListener` to the ListView it doesn't even register my taps. (Log.d on the itemClickListener doesn't ever print)

My row.xml consists of a LinearLayout which has as children a TextView and a RatingBar

I have a feeling that this is because each row has a TextView and a RatingBar which are instead gettnig focus when the item is tapped, so I added `android:descendantFocusability="blocksDescendants"` to their parents' layout in the row.xml, as well as these:

```        
android:focusable="false"
android:clickable="false"
android:focusableInTouchMode="false"
```

to both the TextView and the RatingBar to try to fix the problem, as instructed by this stackoverflow thread: https://stackoverflow.com/questions/5551042/onitemclicklistener-not-working-in-listview

Even after doing this the OnItemClickListener doesn't ever activate. What can I do?

This question would make more sense if you take a look at my code: 

https://github.com/UPB-FILS-MDAD/movierating-application-finicu212/tree/c50fe90120f7901d5c17dc9e25d94402b264dc13/MovieRatingApp

**Comment by finicu212** [comment]
@valexandru @ioanaculic @alexandruradovici

**Comment by finicu212** [comment]
Sorry for the ping... I just got this fixed

The problem was that my custom adapter had a onItemClick function override which was taking priority over my OnItemClickListener...

**Comment by valexandru** [comment]
No problem. It is a good thing that you solved it and also posted what was wrong.
