### ISSUE TITLE
[CityFinder] RemoteService question

### ISSUE THREAD

**Issue by AshLynxu** [UPB-FILS-MDAD/questions#2]
![image](https://user-images.githubusercontent.com/95373290/216792163-11438f25-2bab-46f3-9bcd-fbd5c8993332.png)

In cerinta scrie ca trebuie sa avem 3 foldere diferite pt server, remote service si aplicatia in sine. Asta inseamna ca trebuie sa avem o aplicatie separata care sa fie remote service-ul? Nu putem sa facem serviciul in aceeasi aplicatie?

**Comment by valexandru** [comment]
Salut,

Presupun ca intrebarea ta se refera la daca trebuie facute 3 proiecte separate sau daca poti scrie serviciul in acelasi proiect cu aplicatia principala, nu?
Din punctul meu de vedere, este important sa vad si separat codul pentru serviciu, pentru a avea o structura comuna intre toate proiectele si a cauta mai usor in cod.
Deci, atata timp cat folosesti un [Android Service](https://developer.android.com/guide/components/services), ca in ultimul laborator, si apare si in folderul RemoteService (chit ca e copy-paste), este in regula.
Sper ca ti-am raspuns la intrebare.

**Comment by Kovi12** [comment]
Salut, cam despre cate orase ar trebui sa stocam informatii? Care ar fi un numar acceptabil?

**Comment by valexandru** [comment]
Salut, as vrea sa vad in lista din aplicatie 10-15 orase
